steps:

  - name: docker_gradle
    branches: "master"
    command: bin/ci_build
    agents:
      queue: docker_gradle-restricted

  - wait

  - name: deploy
    branches: "master"
    command: bin/ci_deploy
    agents:
      queue: docker_gradle-restricted

  - name: docker_gradle
    branches: "!master"
    command: bin/ci_build
    agents:
      queue: docker_gradle-unrestricted

  - block: 'Push to Nexus'
    branches: "!master"
    prompt: Push to Nexus?
    fields:
      - select: 'Push'
        key: 'allow-deploy'
        options: ['yes', 'no']
        default: 'no'

  - name: deploy
    branches: "!master"
    command: bin/ci_deploy
    agents:
      queue: docker_gradle-unrestricted
