#!/usr/bin/env bash

set -e -o pipefail -u

SCRIPT="https://package-repository.continuous-integration.cultureamp.net/repository/raw-internal/understand-scaffolding/0.20/buildkite-plugin/hooks/pre-command"
echo "--- Trampolining to $SCRIPT"
source /dev/stdin <<< "$(curl -f "$SCRIPT" || echo false)"
